### PR TITLE
Added Avinash as volunteer

### PR DESCRIPTION
**Pull request by aviboy2006**

### CODE REVIEW

**Review by czynot — APPROVED** [review]
LGTM :)

**Comment by SrushithR** [comment]
Hey Avinash, can you please update the PR with the latest merged changes?

**Comment by aviboy2006** [comment]
> Hey Avinash, can you please update the PR with the latest merged changes?

Done. Can you review once.

**Comment by SrushithR** [comment]
@aviboy2006 your image is coming at the very bottom. Can you please add them to the top, ordered alphabetically?

**Comment by aviboy2006** [comment]
> @aviboy2006 your image is coming at the very bottom. Can you please add them to the top, ordered alphabetically?

Done.

**Review by SrushithR — APPROVED** [review]

**Pull request merged**
